[package]
name = "keypunch"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gvdb-macros = "0.1.12"
include_dir = "0.7.3"
rand = "0.8.5"
rayon = "1.10.0"
strum = "0.26.2"
strum_macros = "0.26.2"
unicode-segmentation = "1.11.0"

[dependencies.gtk]
package = "gtk4"
version = "0.8"
features = ["v4_14", "blueprint"]

[dependencies.adw]
package = "libadwaita"
version = "0.6"
features = ["v1_5"]
